pipeline {
    agent any
    stages {
        stage('Checkout code') {
            steps {
                git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/shallomkanyori/alx-backend-python.git'
            }
        }
        stage('Install dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                source venv/bin/activate
                pip install -r messaging_app/requirements.txt
                '''
            }
        }
        stage('Run tests') {
            steps {
                sh '''
                pip3 install pytest
                source venv/bin/activate
                pytest --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}