pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'messaging-app'
        DOCKER_REGISTRY = 'shallomkanyori'
    }

    stages {
        stage('Checkout code') {
            steps {
                git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/shallomkanyori/alx-backend-python.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                source venv/bin/activate
                pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                pip3 install pytest
                source venv/bin/activate
                pytest --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }

        stage('Build Docker image') {
            steps {
                script {
                    sh '''
                    docker.build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest .
                    '''
                }
            }
        }

        stage('Push Docker image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh '''
                        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
                        docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
                        '''
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}