name: Test Django Messagin App
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: testrootpass
          MYSQL_DATABASE: messaging_app
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 coverage
    
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h 127.0.0.1 --silent; do
          echo "Waiting for MySQL to start..."
          sleep 1
        done
    
    - name: Run flake8 linting
      run: |
        source venv/bin/activate
        flake8 .
      continue-on-error: false
    
    - name: Run migrations
      env:
        MYSQL_ROOT_PASSWORD: testrootpass
        MYSQL_DB: messaging_app
      run: |
        source venv/bin/activate
        python manage.py migrate
      
    - name: Run tests with coverage
      env:
        MYSQL_ROOT_PASSWORD: testrootpass
        MYSQL_DB: messaging_app
      run: |
        source venv/bin/activate
        coverage run --source='.' manage.py test
        coverage xml
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml